version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vsp-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - APP_NAME=${APP_NAME:-VSP Chatbot API}
      - DEBUG=${DEBUG:-False}
    volumes:
      - ./backend:/app/backend
      - ./ai:/app/ai
    restart: unless-stopped
    networks:
      - vsp-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vsp-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - vsp-network

networks:
  vsp-network:
    driver: bridge
